### ISSUE TITLE
Details on GPU Training 

### ISSUE THREAD

**Issue by rayush7** [lorenzo-stacchio/stable-diffusion_custom_inpaint#1]
Hi @lorenzo-stacchio 

Thanks for sharing the code. It's really helpful.

Could you please let me know whether the Tesla V100 GPU (in the Readme) used for training is of 16GB or 32GB configuration? I have 2 Nvidia RTX 2080Ti (12 GB each) but I am getting ```CUDA out of memory error``` even with ```batch-size=2```. Any tricks to reduce the GPU memory usage?

Thanks
Ayush

**Comment by lorenzo-stacchio** [comment]
Hi @rayush7, my Tesla V100 GPU is a 32 GB one. To reduce memory usage I can suggest reducing the input dimension of training images (stable diffusion scales very well at inference with bigger images). For example, you could use as input 256x256 images and then try to inference with 512x512 (if the dataset you used is good, you will see that the generation is quite good). 

Other tricks could be adopting a [lora strategy](https://github.com/cloneofsimo/lora), which is not implemented in this repo. Another strategy would train just the attention layer,  (you could easily implement that by yourself), since they demonstrated to be [enough for training diffusion models](https://github.com/Stability-AI/lora_accelerated#lengthy-introduction). 

Hope that was useful!

Best,

Lorenzo

**Comment by rayush7** [comment]
Thank you @lorenzo-stacchio for sharing all the information and suggestions. I shall work on them.
